language: node_js
node_js:
- '0.11'
- '0.12'
before_script:
- npm install -g bower gulp
- bower install
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: YfjIuOk/HGv0xy/EPSiSYu/oID2KO0g7qo1BKy+Ukj/bjrbl12tItqNYNxVNj3vJvzickLYWsGn2vecQnnAY8Dfp6fWNl11j7JjhNQJDxQhLb+MEDQRclhDSmcsjXlU+WOxtrk0ot3eg6QlGw2vj68c27bOYqY6bSb1bB3Q0Zro=
  app: my-comic-vine
